# Generated by Django 3.1 on 2022-07-24 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppsPaiement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Paiement', 'Paiement'), ('Transfert', 'Transfert'), ('Facture', 'Facture')], default='depense', max_length=25)),
                ('DateTransaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaitingTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Paiement', 'Paiement'), ('Transfert', 'Transfert'), ('Facture', 'Facture')], default='depense', max_length=25)),
                ('DateTransaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.IntegerField()),
            ],
        ),
    ]
