# Generated by Django 3.1 on 2022-07-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppsPaiement', '0002_transaction_waitingtransactions'),
        ('AppsComptes', '0003_auto_20220724_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingtransactions',
            name='receiverPhone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='phone'),
        ),
        migrations.AddField(
            model_name='waitingtransactions',
            name='senderNumCompte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppsComptes.compte'),
        ),
        migrations.AddField(
            model_name='waitingtransactions',
            name='senderPhone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Waitsender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiverPhone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='phone'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='senderNumCompte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppsComptes.compte'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='senderPhone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
