# Generated by Django 3.1 on 2022-08-01 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppsUser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreCarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('PaiementQuotidientLimite', models.IntegerField(default=10)),
                ('MontantPaimentQuotidient', models.IntegerField(default=10000)),
                ('confirmationEnAttente', models.IntegerField(default=0)),
                ('uid', models.CharField(blank=True, max_length=25, null=True)),
                ('privatekey', models.CharField(blank=True, max_length=25, null=True)),
                ('publickey', models.CharField(blank=True, max_length=25, null=True)),
                ('nip', models.CharField(blank=True, max_length=25, null=True)),
                ('initialized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCompte', models.CharField(max_length=25, unique=True)),
                ('nomCompte', models.CharField(blank=True, max_length=25, null=True)),
                ('adresse', models.CharField(blank=True, max_length=25, null=True)),
                ('principal', models.BooleanField(default=True)),
                ('solde', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('professionnel', 'professionnel'), ('depense', 'depense')], default='depense', max_length=25)),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now)),
                ('parametre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppsComptes.parametrecarte')),
                ('permissions', models.ManyToManyField(blank=True, null=True, to='AppsUser.Permissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
