# Generated by Django 3.1 on 2022-07-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsComptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrecarte',
            name='nip',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='parametrecarte',
            name='privatekey',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='parametrecarte',
            name='publickey',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='parametrecarte',
            name='uid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
