# Generated by Django 3.1 on 2022-07-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0001_initial'),
        ('AppsComptes', '0002_auto_20220717_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='NanoPayApp.Permissions'),
        ),
    ]
