# Generated by Django 3.1 on 2022-07-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppsUser', '0002_permissions_userprofile'),
        ('AppsComptes', '0002_compte_parametrecarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='AppsUser.Permissions'),
        ),
        migrations.AddField(
            model_name='compte',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
