# Generated by Django 3.1 on 2022-06-05 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreCarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('PaiementQuotidientLimite', models.IntegerField(default=10000)),
                ('MontantPaimentQuotidient', models.IntegerField(default=10)),
                ('confirmationEnAttente', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('dateDeNaissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=25, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('contacts', models.ManyToManyField(blank=True, related_name='contact', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHeure', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.IntegerField()),
                ('compteEmetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emetteur', to=settings.AUTH_USER_MODEL)),
                ('compteRecepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCompte', models.CharField(default='123', max_length=25)),
                ('nomCompte', models.CharField(blank=True, max_length=25, null=True)),
                ('principal', models.BooleanField(default=True)),
                ('solde', models.IntegerField(default=0)),
                ('type', models.CharField(default='depense', max_length=25)),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now)),
                ('parametre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NanoPayApp.parametrecarte')),
                ('permissions', models.ManyToManyField(blank=True, null=True, related_name='permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
