# Generated by Django 3.1 on 2022-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='valides',
            field=models.BooleanField(default=False),
        ),
    ]
