# Generated by Django 3.1 on 2022-04-13 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrecarte',
            name='paiementVerouiller',
        ),
        migrations.AddField(
            model_name='compte',
            name='parametre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NanoPayApp.parametrecarte'),
        ),
        migrations.AddField(
            model_name='compte',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='perimissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametrecarte',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrecarte',
            name='confirmationEnAttente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compte',
            name='numCompte',
            field=models.CharField(default='123', max_length=25),
        ),
        migrations.AlterField(
            model_name='compte',
            name='type',
            field=models.CharField(default='depense', max_length=25),
        ),
        migrations.AlterField(
            model_name='parametrecarte',
            name='MontantPaimentQuotidient',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='parametrecarte',
            name='PaiementQuotidientLimite',
            field=models.IntegerField(default=10000),
        ),
    ]
