# Generated by Django 3.1 on 2022-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrecarte',
            old_name='nbrPaiementQuotidientLimite',
            new_name='PaiementQuotidientLimite',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
