# Generated by Django 3.1 on 2022-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='comptes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='emetteur',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='recepteur',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='permissions',
            unique_together={('emetteur', 'recepteur', 'comptes')},
        ),
    ]
