# Generated by Django 3.1 on 2022-03-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0002_auto_20220320_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
