# Generated by Django 3.1 on 2022-06-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0002_userprofile_valides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='valide',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='valides',
        ),
    ]
