# Generated by Django 3.1 on 2022-04-18 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0002_auto_20220413_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
