# Generated by Django 3.1 on 2022-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0003_auto_20220604_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
