# Generated by Django 3.1 on 2022-04-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0003_userprofile_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comptes',
        ),
    ]
