# Generated by Django 3.1 on 2022-04-19 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0004_remove_userprofile_comptes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
