# Generated by Django 3.1 on 2022-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0004_auto_20220320_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
