<<<<<<< HEAD
# Generated by Django 3.1 on 2022-04-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0005_auto_20220325_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
=======
# Generated by Django 3.1 on 2022-04-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0005_auto_20220325_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
>>>>>>> 19b0bdf81f71656457920994b7d6f7864e2c1a5c
