# Generated by Django 3.1 on 2022-04-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0006_userprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
