# Generated by Django 3.1 on 2022-04-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0007_userprofile_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='params',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comptes',
            field=models.ManyToManyField(blank=True, related_name='comptes', to='NanoPayApp.Compte'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='nomCompte',
            field=models.CharField(blank=True, default='le nom du compte', max_length=25),
        ),
        migrations.AlterField(
            model_name='compte',
            name='numCompte',
            field=models.IntegerField(default='le nom du compte', unique=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compte',
            name='type',
            field=models.CharField(choices=[('entrprise', 'Entreprise'), ('personel', 'Personel'), ('depense', 'depense')], max_length=25),
        ),
    ]
