# Generated by Django 3.1 on 2022-04-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0008_auto_20220406_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numCompte',
            field=models.CharField(default='le nom du compte', max_length=25),
        ),
    ]
