# Generated by Django 3.1 on 2022-04-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0009_auto_20220407_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='nomCompte',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='type',
            field=models.CharField(choices=[('entrprise', 'Entreprise'), ('personel', 'Personel'), ('depense', 'depense')], default='depense', max_length=25),
        ),
    ]
