# Generated by Django 3.1 on 2022-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoPayApp', '0010_auto_20220407_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
